# Generated by Django 4.1.6 on 2023-05-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("selling_price", models.IntegerField()),
                ("discounted_price", models.IntegerField()),
                ("description", models.TextField()),
                ("composition", models.TextField(default="")),
                ("prodapp", models.TextField(default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sofa", "Sofa"),
                            ("table", "Tables"),
                            ("chair", "Chairs"),
                            ("storage", "Storages"),
                            ("bed", "Beds"),
                            ("desk", "Desks"),
                            ("book", "Bookcases"),
                            ("cup", "Cupboard"),
                        ],
                        max_length=10,
                    ),
                ),
                ("product_image", models.ImageField(upload_to="product")),
            ],
        ),
    ]
