# Generated by Django 4.1.6 on 2023-05-08 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0002_alter_products_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("locality", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=50)),
                ("mobile", models.IntegerField(max_length=50)),
                ("zipcode", models.IntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ALMATY", "ALMATY OBLYSY"),
                            ("ZKO", "ZKO"),
                            ("ATYRAU", "ATYRAU OBLYSY"),
                            ("MANGYSTAU", "MANGYSTAU OBLYSY"),
                            ("AKTOBE", "AKTOBE OBLYSY"),
                            ("KYZYLORDA", "KYZYLORDA OBLYSY"),
                            ("TURKISTAN", "TURKISTAN OBLYSY"),
                            ("KOSTANAY", "KOSTANAY OBLYSY"),
                            ("SKO", "SKO"),
                            ("AKMOLA", "AKMOLA OBLYSY"),
                            ("KARAGANDY", "KARAGANDY OBLYSY"),
                            ("ULYTAU", "ULYTAU OBLYSY"),
                            ("ZHAMBYL", "ZHAMBYL OBLYSY"),
                            ("PAVLODAR", "PAVLODAR OBLYSY"),
                            ("ABAY", "ABAY OBLYSY"),
                            ("ZHETISU", "ZHETISU OBLYSY"),
                            ("VKO", "VKO"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
