# Generated by Django 4.1.6 on 2023-05-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_payment_orderplaced"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="order_id",
            new_name="razorpay_order_id",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="payment_id",
            new_name="razorpay_payment_id",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="payment_status",
            new_name="razorpay_payment_status",
        ),
    ]
