# Generated by Django 4.1.6 on 2023-05-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_review_cover_delete_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="media/review/file"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/review/cover"
            ),
        ),
    ]
