# Generated by Django 4.1.6 on 2023-05-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_products_product_docx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="product_docx",
        ),
    ]
