# Generated by Django 4.1.6 on 2023-05-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_remove_review_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="file",
            field=models.FileField(null=True, upload_to="media/file"),
        ),
    ]
